In [2]:
import numpy as np
import tensorflow as tf

import matplotlib.pyplot as plt

In [3]:
x = tf.Variable(4.0)

with tf.GradientTape() as tape:
    y=x**2

In [4]:
y

<tf.Tensor: shape=(), dtype=float32, numpy=16.0>

In [5]:
dy_dx = tape.gradient(y,x)
dy_dx

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [7]:
w = tf.Variable(tf.random.normal((4,2)))
w

<tf.Variable 'Variable:0' shape=(4, 2) dtype=float32, numpy=
array([[ 0.35413662,  0.01568301],
       [ 0.13210168,  0.49421728],
       [-1.1800941 ,  1.4201925 ],
       [ 1.5987134 , -1.4284658 ]], dtype=float32)>

In [9]:
b = tf.Variable(tf.ones(2, dtype=tf.float32))
b

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [10]:
x = tf.Variable([[10.,20.,30.,40.]], dtype=tf.float32)
x

<tf.Variable 'Variable:0' shape=(1, 4) dtype=float32, numpy=array([[10., 20., 30., 40.]], dtype=float32)>

In [11]:
with tf.GradientTape(persistent=True) as tape:
    y=tf.matmul(x,w)+b
    
    loss = tf.reduce_mean(y**2)

In [12]:
[dl_dw, dl_db] = tape.gradient(loss, [w,b])

In [13]:
dl_dw

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 357.2911 ,  -34.91684],
       [ 714.5822 ,  -69.83368],
       [1071.8733 , -104.75052],
       [1429.1644 , -139.66736]], dtype=float32)>

In [14]:
dl_db

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([35.72911 , -3.491684], dtype=float32)>

In [15]:
layer = tf.keras.layers.Dense(2, activation='relu')

x=tf.constant([[10.,20.,30.]])

In [16]:
with tf.GradientTape() as tape:
    y = layer(x)
    
    loss = tf.reduce_mean(y**2)
grad = tape.gradient(loss,layer.trainable_variables)

In [17]:
grad

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[281.93945,   0.     ],
        [563.8789 ,   0.     ],
        [845.81836,   0.     ]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([28.193945,  0.      ], dtype=float32)>]

In [18]:
x1 = tf.Variable(5.0)
x1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [19]:
x2 = tf.Variable(5.0, trainable=False)
x2

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [20]:
x3 = tf.add(x1,x2)
x3

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [21]:
x4 = tf.constant(5.0)
x4

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [22]:
with tf.GradientTape() as tape:
    y = (x1**2) + (x2**2) + (x3**2) + (x4**2)
    
grad = tape.gradient(y, [x1,x2,x3,x4])

grad

[<tf.Tensor: shape=(), dtype=float32, numpy=10.0>, None, None, None]

In [23]:
x1 = tf.constant(5.0)
x2 = tf.Variable(3.0)

In [33]:
with tf.GradientTape() as tape:
    tape.watch(x1)
    y = (x1**2) + (x2**2)

In [34]:
[dy_dx1, dy_dx2] = tape.gradient(y, [x1,x2]) 

dy_dx1, dy_dx2

(<tf.Tensor: shape=(), dtype=float32, numpy=10.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [35]:
with tf.GradientTape(watch_accessed_variables=False) as tape:
    tape.watch(x1)
    y = (x1**2) + (x2**2)

In [36]:
[dy_dx1, dy_dx2] = tape.gradient(y, [x1,x2]) 

dy_dx1, dy_dx2

(<tf.Tensor: shape=(), dtype=float32, numpy=10.0>, None)

In [37]:
x = tf.constant(1.0)
x1 = tf.Variable(5.0)
x2 = tf.Variable(3.0)

In [38]:
with tf.GradientTape(persistent = True) as tape:
    tape.watch(x)
    
    if x>0.0:
        result = x1**2
    else:
        result = x2**2

dx1, dx2 = tape.gradient(result, [x1,x2])
dx1,dx2

(<tf.Tensor: shape=(), dtype=float32, numpy=10.0>, None)

In [39]:
x = tf.constant(-1.0)
x1 = tf.Variable(5.0)
x2 = tf.Variable(3.0)

In [40]:
with tf.GradientTape(persistent = True) as tape:
    tape.watch(x)
    
    if x>0.0:
        result = x1**2
    else:
        result = x2**2

dx1, dx2 = tape.gradient(result, [x1,x2])
dx1,dx2

(None, <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [43]:
x = tf.Variable(2.)
y = tf.Variable(3.)

with tf.GradientTape() as tape:
    z = y*y
    dy_dx = tape.gradient(z,x)
    
print(dy_dx)

None
