### Basic Tensor Operations

In [1]:
import tensorflow as tf
import numpy as np

tf.debugging.set_log_device_placement(True)

In [2]:
tf.executing_eagerly()

True

In [3]:
x0 = tf.constant(3)

x0

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
print(x0)

tf.Tensor(3, shape=(), dtype=int32)


In [5]:
x0.shape

TensorShape([])

In [7]:
x0.dtype

tf.int32

In [8]:
result0 = x0 +5

result0

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [9]:
result0 = x0 - 5

result0

Executing op Sub in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=-2>

In [12]:
x1 = tf.constant([1.1,2.2,3.3,4.4])

x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [13]:
x1 = x1 + 5

x1

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [15]:
result1 = x1 + tf.constant(5.0)

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


In [16]:
result1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([11.1, 12.2, 13.3, 14.4], dtype=float32)>

In [17]:
x2 = tf.constant([[1,2,3,4],[5,6,7,8]])

x2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [18]:
x2 = tf.cast(x2, tf.float32)

x2

Executing op Cast in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [19]:
result3 = tf.multiply(x1,x2)

result3

Executing op Mul in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 6.1     , 14.4     , 24.900002, 37.6     ],
       [30.5     , 43.199997, 58.100002, 75.2     ]], dtype=float32)>

In [20]:
x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [21]:
arr_x1 = x1.numpy()

arr_x1

array([6.1, 7.2, 8.3, 9.4], dtype=float32)

In [23]:
arr_x4 = np.array([[10,20],[30,40],[50,60]])

arr_x4

array([[10, 20],
       [30, 40],
       [50, 60]])

In [24]:
x4 = tf.convert_to_tensor(arr_x4)

x4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]])>

#### Variables

In [30]:
v1 = tf.Variable([[1.5,2,5],[2,6,8]])

v1

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [35]:
v2 = tf.Variable([[1,2,3],[4,5,6]], dtype=np.float32)
v2

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [39]:
tf.multiply(v1,v2)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Mul in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.5,  4. , 15. ],
       [ 8. , 30. , 48. ]], dtype=float32)>

In [41]:
tf.convert_to_tensor(v1)

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)>

In [42]:
v1.numpy()

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


array([[1.5, 2. , 5. ],
       [2. , 6. , 8. ]], dtype=float32)

In [43]:
v1.assign([[10,20,30],[40,50,60]])

v1

Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)>

In [44]:
v1[0,0].assign(100)

v1

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op StridedSlice in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ResourceStridedSliceAssign in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[100.,  20.,  30.],
       [ 40.,  50.,  60.]], dtype=float32)>

In [45]:
v1.assign_add([[1,1,1],[1,1,1]])
v1

Executing op AssignAddVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[101.,  21.,  31.],
       [ 41.,  51.,  61.]], dtype=float32)>

In [47]:
v1.assign_sub([[1,1,1],[1,1,1]])
v1

Executing op AssignSubVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[100.,  20.,  30.],
       [ 40.,  50.,  60.]], dtype=float32)>

In [48]:
var_a = tf.Variable([2.0,3.0])

var_a

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [50]:
var_b = tf.Variable(var_a)

var_b

Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op DestroyResourceOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [51]:
var_b.assign([200,300])

var_b

Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([200., 300.], dtype=float32)>