In [2]:
import time
import warnings
import logging
import tensorflow as tf

In [3]:
@tf.function
def add(a,b):
    return a+b

@tf.function
def sub(a,b):
    return a-b

@tf.function
def mul(a,b):
    return a*b

@tf.function
def div(a,b):
    return a/b

In [4]:
print(add(tf.constant(5), tf.constant(2)))

tf.Tensor(7, shape=(), dtype=int32)


In [5]:
print(sub(tf.constant(5), tf.constant(2)))

tf.Tensor(3, shape=(), dtype=int32)


In [6]:
print(mul(tf.constant(5), tf.constant(2)))

tf.Tensor(10, shape=(), dtype=int32)


In [7]:
print(div(tf.constant(5), tf.constant(2)))

tf.Tensor(2.5, shape=(), dtype=float64)


In [8]:
@tf.function
def matmul(a,b):
    return tf.matmul(a,b)

In [10]:
@tf.function
def linear(m,x,c):
    return add(matmul(m,x),c)

In [14]:
m = tf.constant([[4.0,5.0,6.0]], tf.float32)

m

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[4., 5., 6.]], dtype=float32)>

In [16]:
x = tf.Variable([[100.0],[100.0],[100.0]], tf.float32)

x

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[100.],
       [100.],
       [100.]], dtype=float32)>

In [17]:
c = tf.constant([[1.0]], tf.float32)

c

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.]], dtype=float32)>

In [18]:
linear(m,x,c)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1501.]], dtype=float32)>

In [19]:
@tf.function
def pos_neg_check(x):
    reduce_sum = tf.reduce_sum(x)
    
    if reduce_sum >0:
        return tf.constant(1)
    elif reduce_sum == 0:
        return tf.constant(0)
    else:
        return tf.constant(-1)

In [20]:
pos_neg_check(tf.constant([100,100]))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [21]:
pos_neg_check(tf.constant([0,0]))

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [22]:
pos_neg_check(tf.constant([-100,-100]))

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [24]:
num = tf.Variable(7)

In [25]:
@tf.function
def add_time(x):
    for i in tf.range(x):
        num.assign_add(x)

In [26]:
add_time(5)

In [27]:
print(num)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=32>


### Python Side Effects

In [32]:
@tf.function
def square(a):
    print('Input a: ', a)
    return a*a

In [33]:
x = tf.Variable([[2,2], [2,2]], dtype = tf.float32)

square(x)

Input a:  <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32>


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>

In [42]:
y = tf.Variable([[2,2], [2,2]], dtype = tf.int32)

square(y)

Input a:  <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32>


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 4],
       [4, 4]])>

In [40]:
z = tf.Variable([[3,3], [3,3]], dtype = tf.float32)

square(z)

Input a:  <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32>


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[9., 9.],
       [9., 9.]], dtype=float32)>

In [47]:
concrete_int_square_fn = square.get_concrete_function(tf.TensorSpec(shape=None, dtype=tf.int32))
concrete_int_square_fn

<ConcreteFunction square(a) at 0x25E2A903B48>

In [48]:
concrete_float_square_fn = square.get_concrete_function(tf.TensorSpec(shape=None, dtype=tf.float32))
concrete_float_square_fn

<ConcreteFunction square(a) at 0x25E2A85BB88>

In [49]:
concrete_int_square_fn(tf.constant([[2,2],[2,2]], dtype = tf.int32))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 4],
       [4, 4]])>

In [51]:
concrete_float_square_fn(tf.constant([[3,3],[3,3]], dtype = tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[9., 9.],
       [9., 9.]], dtype=float32)>

In [52]:
@tf.function
def f(x):
    print("Python execution ", x)
    tf.print('Graph execution ', x)

In [53]:
f(1)

Python execution  1
Graph execution  1


In [54]:
f(1)

Graph execution  1


In [55]:
f("Hello tf.function!")

Python execution  Hello tf.function!
Graph execution  Hello tf.function!
